export const BD_STATIONS = [
  "DHAKA",
  "CHITTAGONG",
  "SYLHET",
  "COX'S BAZAR",
  "RAJSHAHI",
  "KHULNA",
  "RANGPUR",
  "DINAJPUR",
  "MYMENSINGH",
  "COMILLA",
  "BRAHMANBARIA",
  "FENI",
  "BOGRA",
  "SANTAHAR",
  "ISHWARDI",
  "JESSORE",
  "JAMALPUR",
  "KISHOREGANJ",
  "NATORE",
  "SIRAJGANJ",
  "TANGAIL",
  "PARBATIPUR",
  "KUSHTIA",
  "CHUADANGA",
  "LALMONIRHAT",
  "NETROKONA",
  "CHANDPUR",
  "NOAKHALI",
];

export const BD_TRAINS = [
  "ALL MATCHING TRAINS",
  "Subarna Express",
  "Sonar Bangla Express",
  "Mohanagar Provati",
  "Cox's Bazar Express",
  "Tourist Express",
  "Parabat Express",
  "Kalni Express",
  "Jayantik Express",
  "Upaban Express",
  "Silk City Express",
  "Padma Express",
  "Dhumketu Express",
  "Banalata Express",
  "Sundarban Express",
  "Chitra Express",
  "Ekota Express",
  "Drutojan Express",
  "Rangpur Express",
  "Kurigram Express",
  "Teesta Express",
  "Agnibina Express",
  "Jamuna Express",
];

export const BD_CLASSES = [
  "ALL MATCHING CLASSES",
  "Snigdha",
  "AC_B",
  "AC_S",
  "Shovon Chair",
  "Shovon",
  "First Berth",
  "Shulov",
];
